// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4lMwEw_x64dudXa-fHxPX8luX8OndZg',
    appId: '1:840471989431:web:20454cae259daa94e05132',
    messagingSenderId: '840471989431',
    projectId: 'cardapio-coracao-de-mae',
    authDomain: 'cardapio-coracao-de-mae.firebaseapp.com',
    storageBucket: 'cardapio-coracao-de-mae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEXK0pNIBpwfi_PeTxa5mDjx1ijjKbrCw',
    appId: '1:840471989431:android:e873e930ad3ce74de05132',
    messagingSenderId: '840471989431',
    projectId: 'cardapio-coracao-de-mae',
    storageBucket: 'cardapio-coracao-de-mae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXLnhtWHIwX0KA_VbSXNF5fKQN-kwd_xU',
    appId: '1:840471989431:ios:b0fdc35d464d26dde05132',
    messagingSenderId: '840471989431',
    projectId: 'cardapio-coracao-de-mae',
    storageBucket: 'cardapio-coracao-de-mae.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
